version: "3.8"

services:
  api:
    build: ./app
    container_name: observacoes_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgis/postgis:15-3.4
    container_name: weathersense_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./app/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data: